name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: yarn install
    - name: Deploy
      run: npx sst deploy --stage prod
